name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm i

      - name: Compile assets
        run: pnpm build

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
